%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 8.5 and Fixed-Point Designer 5.0           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
% Model of figure 7, the computation engine
function output = fig7model_fixpt(input_fm,output_fm,weights)

    % Assumes that all inputs have been serialized and are proper size

    % variables for number of inputs and outputs
    fm = fimath('RoundingMethod', 'Floor', 'OverflowAction', 'Wrap', 'ProductMode', 'FullPrecision', 'MaxProductWordLength', 128, 'SumMode', 'FullPrecision', 'MaxSumWordLength', 128);

    Tn = fi(64, 0, 7, 0, fm);
    Tm = fi(7, 0, 3, 0, fm);
    output = fi(zeros(1,fi_toint(Tm)), 1, 14, 5, fm);
    
    count = fi(1, 0, 16, 0, fm);
    
    
    for j = coder.unroll(fi(1, 0, 1, 0, fm):Tm)
        for i = coder.unroll(fi(1, 0, 1, 0, fm):Tn)
            output(j) = output_fm(j) + input_fm(Tn)*weights(count);
            
            count(:) = count+fi(1, 0, 1, 0, fm);
        end
    end
    
end



function y = fi_toint(u)
    coder.inline( 'always' );
    if isfi( u )
        nt = numerictype( u );
        s = nt.SignednessBool;
        wl = nt.WordLength;
        y = int32( fi( u, s, wl, 0, hdlfimath ) );
    else
        y = int32( u );
    end
end
